---
name: Package
description: Install python and package
runs:
    using: "composite"
    steps:

      - name: Install dependencies
        run: |
          pip install -r dev_requirements.txt
        shell: bash

      - name: List dependencies
        run: |
          pip list
        shell: bash
