name: Pip install debug

on:
  push:



jobs:

  e2e:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Python ${{ inputs.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip debug install grpcio --verbose
        shell: bash

      - name: Install dependencies2
        run: |
          pip install --upgrade pip
          pip install grpcio=1.50.0 --verbose
        shell: bash
