name: Pip install debug

on:
  push:

jobs:
  e2e:
    runs-on: macos-12
    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: MacOS Version
        run: |
          sw_vers -productVersion
        shell: bash

      - name: Debug
        run: |
          pip install --upgrade pip
          pip debug --verbose
        shell: bash
